apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::405165060795:role/UdacityFlaskDeployCBKubectlRole
      username: build      
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::405165060795:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-8SRR6JPYGOLA
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-08-21T01:18:57Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1360"
  uid: 81a0160f-39fa-4eb6-b5ef-8301a6fd5657
